import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '../../sections'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body className="bg-[#1C1B20]">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
